# Define a list of upstream channels to act as a gateway for. Currently
# we will support only path based routing. This can be enhanced to
# support host based routing as well
upstreams:
- name: maven-central
  type: maven2
  authentication:
    type: basic
  route:
    prefix: /maven2
  repository:
    host: repo.maven.apache.org
    port: 443
    tls: true
    sni: repo.maven.apache.org
    authentication: {}
- name: pypi-org
  type: pypi
  authentication:
    type: noauth
  route:
    prefix: /pypi
  repository:
    host: pypi.org
    port: 443
    tls: true
    sni: pypi.org
    authentication: {}
messaging:
  url: tls://nats-server:4222
tap:
  publisher:
    topics:
      upstream_request: com.msg.event.upstream.request
      upstream_response: com.msg.event.upstream.response
pdp:
  publisher:
    topics:
      policy_denied: com.msg.event.pdp.policy_denied
